@startuml

enum TipoParada{
    BUS
    TAXI
    TREN

    + getImagen()
    + getTipo()
}

interface Builder{
    construir()
}

class Parada{
    - codigo: String
    - nombre: String
    - tipo: TipoParada
    - direccion: String
}

class Ruta{
    - codigo: String
    - nombre: String
    - origen: Parada
    - destino: Parada
    - distancia: float
    - tiempo: float
    - costo: float
    - trasbordos: int

    + toString()
}

class RutaBuilder{
    - Ruta ruta
    + setCodigo()
    + setNombre()
    + setOrigen()
    + setDestino()
    + setDistancia()
    + setTiempo()
    + setCosto()
    + setTrasbordos()
}

Builder <|-- RutaBuilder

enum Colores{
    FONDO
    ENFASIS
    DETALLES
    DECORATIVOS

    + getColor()
}

interface CRUD{
    insertar()
    eliminar()
    actualizar()
}

@enduml